### ISSUE TITLE
[Bug] TRADFRI bulb E27 state not updated

### ISSUE THREAD

**Issue by duculete** [itavero/homebridge-z2m#445] opened 2022-05-22 07:31 UTC
Using zigbee2mqtt latest version with homebridge-z2m. One of the zigbee devices is https://www.zigbee2mqtt.io/devices/LED1732G11.html#ikea-led1732g11

Problem: When I control light bulb from home app, the state is not updated:
example: 

- light is off, i turn it on from home app, it will stay on for 1 second then turn off (just in home app, the light is still on). if i press again in home app on the light, it will "stay" on. 
- light is off, i press on home app to turn it on, it will stay on for 1 second then display as off (only in home app), in reality the light bulb remains on. if i press again on homeapp accessory it will remain on.
- go to zigbee2mqtt ui and manually turn on/off the bulb, the state is updated ok in home app.
- manually publish "{"state":"OFF"} of {"state":"ON"} to MQTT topic, bulb will turn off or on and the state in home app will update as expected
Only when i control the accessory from home app, the state will not be updated in home app.

```
{
            "mqtt": {
                "base_topic": "zigbee2mqtt",
                "server": "mqtt://MY_MQ_IP:MY_MQ_PORT",
                "reject_unauthorized": false,
                "keepalive": 60,
                "version": 4
            },
            "defaults": {
                "exclude": false
            },
            "platform": "zigbee2mqtt"
        },
```

Homebridge Zigbee2MQTT: homebridge-z2m v1.8.0

**Comment by itavero** [comment] 2022-05-22 07:59
sounds like a duplicate of #383. Please try to workaround mentioned there.

**Comment by duculete** [comment] 2022-05-22 10:57
Thanks,

that fix it.

**Comment by duculete** [comment] 2022-05-22 10:58
duplicate of https://github.com/itavero/homebridge-z2m/issues/383

**Comment by duculete** [comment] 2022-05-22 10:58
duplicate of https://github.com/itavero/homebridge-z2m/issues/383

**Closed** 2022-05-22 10:59 UTC
Labels: bug
