### ISSUE TITLE
[Bug] problem after upgrading zigbee2mqtt to 1.35

### ISSUE THREAD

**Issue by Ropuh** [itavero/homebridge-z2m#794] opened 2024-01-01 13:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Crash of the plugin
```
[1/1/2024, 12:58:42 PM] [homebridge-z2m] Publish to 'zigbee2mqtt/0x680ae2fffe3fdfe4/get': '{"state":0}'
[1/1/2024, 12:58:42 PM] [homebridge-z2m] Publish to 'zigbee2mqtt/0xa4c1385d85a35265/get': '{"state":0}'
TypeError: Cannot read properties of null (reading 'vendor')
at isDeviceDefinition (/usr/lib/node_modules/homebridge-z2m/src/z2mModels.ts:294:73)
at Zigbee2mqttAccessory.updateDeviceInformation (/usr/lib/node_modules/homebridge-z2m/src/platformAccessory.ts:290:30)
at new Zigbee2mqttAccessory (/usr/lib/node_modules/homebridge-z2m/src/platformAccessory.ts:82:10)
at Zigbee2mqttPlatform.addAccessory (/usr/lib/node_modules/homebridge-z2m/src/platform.ts:419:19)
at Zigbee2mqttPlatform.configureAccessory (/usr/lib/node_modules/homebridge-z2m/src/platform.ts:319:10)
at /usr/lib/node_modules/homebridge/src/bridgeService.ts:328:25
at Array.filter ()
at BridgeService.restoreCachedPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:288:69)
at ChildBridgeFork.startBridge (/usr/lib/node_modules/homebridge/src/childBridgeFork.ts:186:24)
[1/1/2024, 12:58:43 PM] [homebridge-z2m] Child bridge process ended
[1/1/2024, 12:58:43 PM] [homebridge-z2m] Process Ended. Code: 1, Signal: null
[1/1/2024, 12:58:50 PM] [homebridge-z2m] Restarting Process...
[1/1/2024, 12:58:54 PM] [homebridge-z2m] Launched child bridge with PID 3760
[1/1/2024, 12:58:55 PM] Registering platform 'homebridge-z2m.zigbee2mqtt'
[1/1/2024, 12:58:55 PM] [homebridge-z2m] Loaded homebridge-z2m v1.9.2 child bridge successfully
[1/1/2024, 12:58:56 PM] Loaded 70 cached accessories from cachedAccessories.0E9CACDE5EA2.
[1/1/2024, 12:58:57 PM] [homebridge-z2m] Connecting to MQTT server at mqtt://127.0.0.1:1883
[1/1/2024, 12:58:58 PM] [homebridge-z2m] Restoring accessory: Sypialnia Computer Switch (0x00158d0004506dde)
```

### This plugin

1.9.2

### Homebridge

1.7.0

### Zigbee2MQTT

1.35

### Homebridge Config UI X (if applicable)

4.54.1

**Comment by itavero** [comment] 2024-01-01 13:26
Are you using a device that's unsupported by Zigbee2MQTT?

Can you share (e.g. attach) your device list from `zigbee2mqtt/bridge/devices` (or at least the entry of the device triggering this error)?

**Comment by itavero** [comment] 2024-01-01 13:37
Potentially a duplicate of #782

**Comment by itavero** [comment] 2024-01-01 13:43
Seems that I have implemented [this check](https://github.com/itavero/homebridge-z2m/blob/v1.11.0-beta.2/src/z2mModels.ts#L302) incorrectly.
It also seems that there are now (e.g. starting the latest Zigbee2MQTT release) devices that do not contain a `vendor`.

If someone can share the entries from `zigbee2mqtt/bridge/devices` that do not contain a `vendor`, that would be great. Not sure when I'll have time to patch this though, but I do want to make sure that there's no other keys missing/optional now.

**Comment by puijken** [comment] 2024-01-01 15:23
Rolling back to zigbee2mqtt 1.34 fixes the issue .. so it's for sure related to the new release. Support was added for "unsupported" devices to have basic functionality working even if it is not officially supported by zigbee2mqtt.

Probably related? - https://github.com/Koenkk/zigbee2mqtt/releases

**Comment by Ropuh** [comment] 2024-01-01 15:54
`
{"attribute":"currentSummDelivered","cluster":"seMetering","maximum_report_interval":3600,"minimum_report_interval":5,"reportable_change":[1,1]}],"scenes":[]},"242":{"bindings":[],"clusters":{"input":[],"output":["greenPower"]},"configured_reportings":[],"scenes":[]}},"friendly_name":"Salon Choinka","ieee_address":"0xa4c1385d85a35265","interview_completed":true,"interviewing":false,"manufacturer":"_TZ3000_gjnozsaz","model_id":"TS011F","network_address":58994,"power_source":"Mains (single phase)","supported":true,"type":"Router"},
`
works zigbee2mqtt 1.34 and crash after upgrading to 1.35

**Comment by Jeepmg** [comment] 2024-01-01 15:56
> Rolling back to zigbee2mqtt 1.34 fixes the issue .. so it's for sure related to the new release. Support was added for "unsupported" devices to have basic functionality working even if it is not officially supported by zigbee2mqtt.

How to roll back to 1.34 ?

**Comment by puijken** [comment] 2024-01-01 16:26
> > Rolling back to zigbee2mqtt 1.34 fixes the issue .. so it's for sure related to the new release. Support was added for "unsupported" devices to have basic functionality working even if it is not officially supported by zigbee2mqtt.
> 
> Same problem with Profalux devices
> 
> How to roll back to 1.34 ?
> 
> Thank you

Depens on your setup .. I have all running in containers so just change the tag from "koenkk/zigbee2mqtt:latest" to "koenkk/zigbee2mqtt:1.34.0" did the trick for me :)

If you're not running it in containers it might be more difficult..

**Comment by Rene1695** [comment] 2024-01-01 17:14
Hey,

same issue for me. I was on v1.9 and upgraded to 1.9.2. Why are you on 1.34? I can even select this in the child bridge "version tab" 

![image](https://github.com/itavero/homebridge-z2m/assets/71972934/c0645c7e-8318-4b7e-addd-c3f5da6e969f)

However, once I go back to 1.9 or any version below, I have still the same issue. Somebody has an idea why this is the case?

**Comment by puijken** [comment] 2024-01-01 17:16
> Hey,
> 
> same issue for me. I was on v1.9 and upgraded to 1.9.2. Why are you on 1.34? I can even select this in the child bridge "version tab"
> 
> ![image](https://private-user-images.githubusercontent.com/71972934/293598943-c0645c7e-8318-4b7e-addd-c3f5da6e969f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMjk2MTksIm5iZiI6MTcwNDEyOTMxOSwicGF0aCI6Ii83MTk3MjkzNC8yOTM1OTg5NDMtYzA2NDVjN2UtODMxOC00YjdlLWFkZGQtYzNmNWRhNmU5NjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE3MTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YTQ4MjdmYjEzMTc2Mjc0MDc0YTBiMmI1MjlkNTZhODRmNDc0YWNjMjRmN2Q0Njg3NjY3ZWYyZmJmYTU1MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zpKcejjH9Ec42IE6KqTRiy_II4XrhgosZouSJ0LC8pE)
> 
> However, once I go back to 1.9 or any version below, I have still the same issue. Somebody has an idea why this is the case?

I'm talking about the Zigbee2MQTT version - not the Homebridge version and not the homebridge-z2m version. The issue probably lies in a change done in Zigbee2MQTT as referenced to a couple of posts above.

**Comment by Wrangler-93** [comment] 2024-01-01 17:22
I went back to "koenkk/zigbee2mqtt:1.34.0" but still the same , had an error on a EW-Link device, removed it from zigbee2mqtt but Homebridge still gives the error on that device?!?!
Any ideas how to remove that device from homebridge??

**Comment by puijken** [comment] 2024-01-01 17:24
You can remove it from the "cached accessories"

Homebridge GUI -> 3 dots at the top right -> Homebridge Settings -> Remove Single Cached Accessory (almost at the bottom of the page)

**Comment by Wrangler-93** [comment] 2024-01-01 17:43
> You can remove it from the "cached accessories"
> 
> Homebridge GUI -> 3 dots at the top right -> Homebridge Settings -> Remove Single Cached Accessory (almost at the bottom of the page)

This worked for me, all up and running again!!

Thanx

**Comment by Veldkornet** [comment] 2024-01-01 23:09
For me, I noticed that there was a new "Coordinator" device added after the new z2m release. I just added this to the excluded devices in the HomeBridge plugin settings, and then it started up fine.

**Comment by itavero** [comment] 2024-01-02 05:13
> For me, I noticed that there was a new "Coordinator" device added after the new z2m release.

If I remember correctly this was there before as well, but I had some code to ignore it.

I was hoping to dive into this issue yesterday evening, but unfortunately I got an ocular migraine attack, so no screens for me.

Hopefully I'll manage this evening. It sounds like it should be an easy fix.

PS: not yet sure if I'll first patch v1.9.2 (and make a v1.9.3) and then merge it into `master` or the other way around.

**Comment by itavero** [comment] 2024-01-02 05:24
Any chance that someone still has an export of `zigbee2mqtt/bridge/devices` from when the system was running the latest Zigbee2MQTT release?

I'd love to see the entry of the coordinator.
It was there before, so I'm curious what changed.

I'm running Zigbee2MQTT v1.34.0 and it looks more or less like this:

```jsonc
{
  "definition": null,
  "disabled": false,
  "endpoints": {
    /* lots of endpoints here */
    }
  },
  "friendly_name": "Coordinator",
  "ieee_address": "0x00124b001caa69fc",
  "interview_completed": true,
  "interviewing": false,
  "network_address": 0,
  "supported": false,
  "type": "Coordinator"
}
```

**Comment by itavero** [comment] 2024-01-02 05:30
Got this from the log from @mrmaximas. It seems that the `supported` flag changed.

```jsonc
{
  "definition": null,
  "disabled": false,
  "endpoints": {
    /* lots of endpoints */
  },
  "friendly_name": "Coordinator",
  "ieee_address": "0x00124b002a1aa3c4",
  "interview_completed": true,
  "interviewing": false,
  "network_address": 0,
  "supported": true,
  "type": "Coordinator"
}
```

**Comment by fiftysomethingguy** [comment] 2024-01-02 13:25
Thanks for looking into this.Z2M 1.35.0 killed my install as well. Reverted back to 1.34.0 and works again. Will be really grateful this can be fixed as 1.35.0 supports the new Ikea Parasoll contact sensors that I'd like to purchase.

**Comment by mrmaximas** [comment] 2024-01-02 13:27
> Thanks for looking into this.Z2M 1.35.0 killed my install as well. Reverted back to 1.34.0 and works again. Will be really grateful this can be fixed as 1.35.0 supports the new Ikea Parasoll contact sensors that I'd like to purchase.

add ieee address of coordinator to exclusions and enjoy 1.35.0

**Comment by puijken** [comment] 2024-01-02 13:28
For me the "workaround" of @Veldkornet seemed to work -> https://github.com/itavero/homebridge-z2m/issues/794#issuecomment-1873518037

I'm back on Z2M 1.35.0 but with the "Coordinator" device exluded in the homebridge-z2m plugin in homebridge.

**Comment by Jeepmg** [comment] 2024-01-02 14:12
> For me the "workaround" of @Veldkornet seemed to work -> [#794 (comment)](https://github.com/itavero/homebridge-z2m/issues/794#issuecomment-1873518037)

+1

**Comment by itavero** [comment] 2024-01-02 19:12
Anyone here that's still running v1.9.2 of the plugin thats willing to try a version that should include the fix for this?

Still need to make that release though, just checking if someone's up for it.

Based on earlier findings I'm pretty sure it will fix it, but it would be nice to get some confirmation from others.

**Comment by fiftysomethingguy** [comment] 2024-01-02 19:51
I'll try it. No problem.

**Comment by itavero** [comment] 2024-01-02 20:09
Just published [v1.9.3-rc.0](https://www.npmjs.com/package/homebridge-z2m/v/1.9.3-rc.0) to NPM.

I believe this should solve the problem, but unfortunately I don't have time to update Zigbee2MQTT on my production environment now to test it with the latest Zigbee2MQTT release.

If you tried it (can even be on a separate machine connecting to the same MQTT broker that your production environment is connected to), let me know if it works without the aforementioned workaround.

**Comment by fiftysomethingguy** [comment] 2024-01-02 23:31
v1.9.3-rc.0 works fine with the workaround removed. Many thanks.

**Comment by jfcabral** [comment] 2024-01-02 23:43
> Just published [v1.9.3-rc.0](https://www.npmjs.com/package/homebridge-z2m/v/1.9.3-rc.0) to NPM.
> 
> I believe this should solve the problem, but unfortunately I don't have time to update Zigbee2MQTT on my production environment now to test it with the latest Zigbee2MQTT release.

I have Zigbee2MQTT [1.35.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.35.0) and after updating `homebridge-z2m` to [`v1.9.3-rc.0`](https://github.com/itavero/homebridge-z2m/releases/tag/v1.9.3-rc.0) the issue was solved without any further change!

Thank you @itavero for the quick fix! 😄

**Comment by itavero** [comment] 2024-01-03 05:08
Thanks for the feedback. I'll try to make it a "regular" release and to merge it into the beta versions later today.

**Comment by Jeepmg** [comment] 2024-01-03 05:26
I just installed version V 1.9.3 rc and removed the workout. Everything seems to be back to normal.

thank you very much for your responsiveness and this quick repair.

**Comment by Wrangler-93** [comment] 2024-01-03 08:51
> Just published [v1.9.3-rc.0](https://www.npmjs.com/package/homebridge-z2m/v/1.9.3-rc.0) to NPM.
> 
> I believe this should solve the problem, but unfortunately I don't have time to update Zigbee2MQTT on my production environment now to test it with the latest Zigbee2MQTT release.
> 
> If you tried it (can even be on a separate machine connecting to the same MQTT broker that your production environment is connected to), let me know if it works without the aforementioned workaround.

works here too, great work 👍

**Comment by Ropuh** [comment] 2024-01-03 08:54
> Just published [v1.9.3-rc.0](https://www.npmjs.com/package/homebridge-z2m/v/1.9.3-rc.0) to NPM.
> 
> I believe this should solve the problem, but unfortunately I don't have time to update Zigbee2MQTT on my production environment now to test it with the latest Zigbee2MQTT release.
> 
> If you tried it (can even be on a separate machine connecting to the same MQTT broker that your production environment is connected to), let me know if it works without the aforementioned workaround.

I just installed version V 1.9.3 rc.0 everything seems to be OK.
Thank you

**Comment by itavero** [comment] 2024-01-03 19:00
Just promoted `v1.9.3-rc.0` to a regular release (`v1.9.3`) and pushed it to the `latest` tag.

I'll merge it back to `master` now and start working on making a `v1.11.0-beta.3`.

**Comment by jfcabral** [comment] 2024-01-03 19:50
> Just promoted `v1.9.3-rc.0` to a regular release (`v1.9.3`) and pushed it to the `latest` tag.
> 
> I'll merge it back to `master` now and start working on making a `v1.11.0-beta.3`.

I've just upgraded to [Release 1.9.3](https://github.com/itavero/homebridge-z2m/releases/tag/v1.9.3)  and it seems to be working properly ✔️ 

Before I was using [Release 1.11.0-beta.2](https://github.com/itavero/homebridge-z2m/releases/tag/v1.11.0-beta.2) but I had to downgrade due to this issue... So when you create `v1.11.0-beta.3` I volunteer to test it 😄 

Thank you once again @itavero

**Comment by itavero** [comment] 2024-01-03 21:26
Seems like a introduced another bug on the `master` branch earlier this week, so no new beta just yet.
I expect it will be relatively easy to solve, just a matter of finding some time to do so 😅

**Comment by itavero** [comment] 2024-01-04 19:41
[Release v1.11.0-beta.3](https://github.com/itavero/homebridge-z2m/releases/tag/v1.11.0-beta.3) has also been published.

I'm going to install it myself now as well.

**Comment by jfcabral** [comment] 2024-01-04 21:09
> [Release v1.11.0-beta.3](https://github.com/itavero/homebridge-z2m/releases/tag/v1.11.0-beta.3) has also been published.
> 
> I've installed it myself and also updated Zigbee2MQTT. No noticeable issues so far.

Thank you @itavero, I too have just installed it, and so far so good 👍

**Comment by nefh** [comment] 2024-01-05 15:43
I have also problems after upgrading to 1.35 that seem to be connected with homebridge-z2m. Please have a look on issue list of zigbee2mqtt github:

[https://github.com/Koenkk/zigbee2mqtt/issues/20526](url)

The issue is still present with v.1.11.0-beta.3, here are the logs from zigbee2mqtt:
[log.txt](https://github.com/itavero/homebridge-z2m/files/13843909/log.txt)

**Comment by itavero** [comment] 2024-01-06 06:07
> I have also problems after upgrading to 1.35 that seem to be connected with homebridge-z2m.

> The issue is still present with v.1.11.0-beta.3, here are the logs from zigbee2mqtt:

This is an issue in Zigbee2MQTT. Not the issue being discussed here.

From what I can tell it's also not caused by homebridge-z2m. It just gets more visible because the plugin starts requesting information from devices (like blinds).

**Closed** 2024-05-21 20:06 UTC
Labels: bug
