### ISSUE TITLE
[Device] IKEA E2007 Air Purifier - Missing features

### ISSUE THREAD

**Issue by ComicBit** [itavero/homebridge-z2m#592] opened 2022-12-15 14:46 UTC
**Device description**
IKEA E2007 Air Purifier

**Supported in Zigbee2MQTT?**
It's already fully supported

**Device model / Exposes information**
STARKVIND Air purifier table

**Missing features/functionality**
Hello, the IKEA Air Purifier have some good functionalities which would be very helpful if exposed on the plugin.
mode, fan_speed, led_enable, child_lock, replace_filter would be all very useful to be showed. Especially for mode and fan speed.

**Suggested services and characteristics**
I guess that some of the functionalities could be adapted using the Air Purifier mode. The only thing missing would be for filter which supposedly should be just a simple sensor which gives back a boolean and the other is auto mode which could maybe be managed as a trigger.

**Comment by itavero** [comment] 2022-12-15 15:45
Duplicate of #333. I'd suggest to continue the discussion there.

**Closed by itavero** 2022-12-15 15:45 UTC
Labels: enhancement
