### ISSUE TITLE
[Device] STARKVIND Air Purifier

### ISSUE THREAD

**Issue by Avamander** [itavero/homebridge-z2m#669] opened 2023-04-12 17:24 UTC
### Device Model

STARKVIND Air purifier

### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find an existing issue.

### Supported by Zigbee2MQTT?

- [X] Device is supported by Zigbee2MQTT

### Missing features / functionality

Fan speed / fan modes
LED control
Child Lock control
Filter expiration

### HomeKit Services and Characteristics

Air Purifier `000000BB-0000-1000-8000-0026BB765291` and Lock Physical Controls `000000A7-0000-1000-8000-0026BB765291`  for example.

Plugins such as `homebridge-miot` seem to implement these features.

### Exposes information from Zigbee2MQTT

```json
{
    "air_quality": "excellent",
    "child_lock": "UNLOCK",
    "fan_mode": "7",
    "fan_speed": 7,
    "fan_state": "ON",
    "led_enable": true,
    "linkquality": 142,
    "pm25": 0,
    "replace_filter": false,
    "update": {
        "installed_version": 69633,
        "latest_version": 69633,
        "state": "idle"
    },
    "device": {
        "applicationVersion": 16,
        "dateCode": "20220518",
        "friendlyName": "0x0000000000000000",
        "hardwareVersion": 1,
        "ieeeAddr": "0x0000000000000000",
        "manufacturerID": 4476,
        "manufacturerName": "IKEA of Sweden",
        "model": "E2007",
        "networkAddress": 48841,
        "powerSource": "Mains (single phase)",
        "softwareBuildID": "1.1.001",
        "stackVersion": 103,
        "type": "Router",
        "zclVersion": 8
    },
    "update_available": null
}
```

**Comment by itavero** [comment] 2023-04-12 18:27
Duplicate of #333

**Closed by itavero** 2023-04-12 18:27 UTC
Labels: enhancement

**Comment by itavero** [comment] 2023-04-12 19:22
You are requesting the same as was being discussed there, right? Or am I missing something?

**Comment by Avamander** [comment] 2023-04-12 20:12
Hmm, I think the general intent is the same. Though ideally an unresolved issue would remain open.
