### ISSUE TITLE
[Bug] characteristic was supplied illegal value (DIYRuZ_Flower)

### ISSUE THREAD

**Issue by ryoko-sky** [itavero/homebridge-z2m#234] opened 2021-07-14 03:15 UTC
conveys the value incorrectly 

DIYRuZ DIYRuZ_Flower
https://z2m.dev/devices/diyruz/diyruz_flower.html

log plugin [7/14/2021, 1:06:18 PM] [homebridge-z2m] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info

everything is updated to the latest version

**Comment by ryoko-sky** [comment] 2021-07-14 03:16
![image](https://user-images.githubusercontent.com/14962706/125555377-5727fc7c-414b-4692-9274-59a44bf88779.png)

**Comment by itavero** [comment] 2021-07-14 04:18
Can you please provide all the information requested in the issue template?

**Comment by ryoko-sky** [comment] 2021-07-14 05:22
does not transmit light and humidity

**Comment by itavero** [comment] 2021-07-14 06:17
> does not transmit light and humidity

I assume that Zigbee2MQTT indicates that the device does provide this information (in the `exposes` information).
If it does not, that sounds like a bug in Zigbee2MQTT or the device, rather than this plugin.

Unless the information requested in the Bug Report template is provided, there's not really anything I can do to investigate this bug.

**Comment by ryoko-sky** [comment] 2021-07-14 11:25
![image](https://user-images.githubusercontent.com/14962706/125614092-4f6ef2c8-fcb3-4be9-b0be-eee071a66310.png)
logging is correct. in ui z2m the indicators are correct

**Comment by ryoko-sky** [comment] 2021-07-14 11:29
![image](https://user-images.githubusercontent.com/14962706/125614696-c1a2bc2c-b1e8-430a-b785-9ed6ce7229c8.png)
this is what the plugin says in advanced mode

**Comment by itavero** [comment] 2021-07-14 12:03
The device clearly isn't sending the temperature and humidity, but Zigbee2MQTT says that is _should_ send this.
Do you expect the device to report a temperature and humidity?

If not, I would suggest to [exclude the properties for this device](https://z2m.dev/config.html#devices) in your Homebridge configuration.

_Once again, it would have helped if you would have filled in the bug report template: this also asks you to describe the problem and the behavior you expected instead.
Also "latest" versions doesn't say anything, because this issue wil still exist in a year and for sure the version of (some of) the components will have changed._

**Comment by ryoko-sky** [comment] 2021-07-14 12:07
> ![изображение](https://user-images.githubusercontent.com/14962706/125614092-4f6ef2c8-fcb3-4be9-b0be-eee071a66310.png)
> ведение журнала правильное. в ui z2m индикаторы верные

**Comment by itavero** [comment] 2021-07-14 12:13
> > ![изображение](https://user-images.githubusercontent.com/14962706/125614092-4f6ef2c8-fcb3-4be9-b0be-eee071a66310.png)
> > ведение журнала правильное. в ui z2m индикаторы верные

The logging shows `null` for `humidity` and `null` for `temperature_bme`.. that's not a valid value and I expect it's not even in the range specified in the `exposes` information.

Anyway, until you provide the information requested in the Bug Report template (including the expected behavior, steps to reproduce and exposes information), I can't help you any further.

**Comment by ryoko-sky** [comment] 2021-07-14 12:47
** Describe the bug **

does not transmit information

** Related devices **

https://z2m.dev/devices/diyruz/diyruz_flower.html

** To Reproduce **

1.it is possible to reproduce since it did not work in homekit
2. MQTT publish: topic 'zigbee2mqtt / Rastishka', payload '{"battery": 100, "humidity": null, "illuminance": 5390, "illuminance_lux": 3, "linkquality": 55, "pressure": null , "soil_moisture": 92, "temperature_bme": null, "temperature_ds": 23.5, "voltage": 3100} '

it is not controlled but only collects information

** Expected behavior **

should show temperature, humidity, brightness, and charge level

** MQTT messages **

MQTT publish: topic 'zigbee2mqtt / Rastishka', payload '{"battery": 100, "humidity": null, "illuminance": 5390, "illuminance_lux": 3, "linkquality": 55, "pressure": null, " soil_moisture ": 92," temperature_bme ": null," temperature_ds ": 23.5," voltage ": 3100} '

** Plugin messages **
[7/14/2021, 10:27:25 PM] [homebridge-z2m] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[7/14/2021, 10:27:25 PM] [homebridge-z2m] Error:
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1891:14)
    at CurrentTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at TemperatureSensor.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at PassthroughCharacteristicMonitor.callback (/homebridge/node_modules/homebridge-z2m/src/converters/monitor.ts:28:24)
    at /homebridge/node_modules/homebridge-z2m/src/converters/basic_sensors.ts:114:34
    at Array.forEach (<anonymous>)
    at TemperatureSensorHandler.updateState (/homebridge/node_modules/homebridge-z2m/src/converters/basic_sensors.ts:114:19)
    at Zigbee2mqttAccessory.updateStates (/homebridge/node_modules/homebridge-z2m/src/platformAccessory.ts:294:15)
    at Zigbee2mqttPlatform.handleDeviceUpdate (/homebridge/node_modules/homebridge-z2m/src/platform.ts:189:19)
[7/14/2021, 10:27:25 PM] [zigbee2mqtt] Handled device update for Rastishka: {"battery": 100, "humidity": null, "illuminance": 5390, "illuminance_lux": 3, "linkquality ": 55," pressure ": null," soil_moisture ": 86," temperature_bme ": null," temperature_ds ": 32.75," voltage ": 3100}

** Versions used **
Please provide the version of the following pieces of software:
 - This plugin - 1.3.0
 - Homebridge - 1.3.4
 - Zigbee2MQTT - 1.20.0
 - Homebridge Config UI X - 4.41.1


my guess is that he transfers this to non-standard topics
eg

humidity in topic soil_moisture

**Comment by ryoko-sky** [comment] 2021-07-14 12:48
can i provide anything else to solve this problem?

**Comment by itavero** [comment] 2021-07-14 12:58
Please provide the following:
* The device entry from `zigbee2mqtt/bridge/devices` (note: this is different from `zigbee2mqtt/bridge/config/devices`)

Also please put JSON messages and such in code blocks.

**Comment by ryoko-sky** [comment] 2021-07-14 13:22
I'm not sure if I understood correctly, so I provided both options
`[{"definition":null,"endpoints":{"1":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"10":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"11":{"bindings":[],"clusters":{"input":["ssIasAce"],"output":["ssIasZone","ssIasWd"]},"configured_reportings":[]},"110":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"12":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"13":{"bindings":[],"clusters":{"input":["genOta"],"output":[]},"configured_reportings":[]},"2":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"242":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"3":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"4":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"47":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"5":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"6":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]},"8":{"bindings":[],"clusters":{"input":[],"output":[]},"configured_reportings":[]}},"friendly_name":"Coordinator","ieee_address":"0x00124b0018f1da45","interview_completed":true,"interviewing":false,"network_address":0,"supported":false,"type":"Coordinator"},{"definition":{"description":"Multipurpose sensor (2018 model)","exposes":[{"access":1,"description":"Measured temperature value","name":"temperature","property":"temperature","type":"numeric","unit":"°C"},{"access":1,"description":"Indicates if the contact is closed (= true) or open (= false)","name":"contact","property":"contact","type":"binary","value_off":true,"value_on":false},{"access":1,"description":"Indicates if the battery of this device is almost empty","name":"battery_low","property":"battery_low","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Indicates whether the device is tampered","name":"tamper","property":"tamper","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Indicates if the device is moving","name":"moving","property":"moving","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Accelerometer X value","name":"x_axis","property":"x_axis","type":"numeric"},{"access":1,"description":"Accelerometer Y value","name":"y_axis","property":"y_axis","type":"numeric"},{"access":1,"description":"Accelerometer Z value","name":"z_axis","property":"z_axis","type":"numeric"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"IM6001-MPP01","supports_ota":false,"vendor":"SmartThings"},"endpoints":{"1":{"bindings":[{"cluster":"msTemperatureMeasurement","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}},{"cluster":"genPowerCfg","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}},{"cluster":"manuSpecificSamsungAccelerometer","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}}],"clusters":{"input":["genBasic","genPowerCfg","genIdentify","genPollCtrl","msTemperatureMeasurement","ssIasZone","haDiagnostic","manuSpecificSamsungAccelerometer"],"output":["genIdentify","genOta"]},"configured_reportings":[{"attribute":"measuredValue","cluster":"msTemperatureMeasurement","maximum_report_interval":3600,"minimum_report_interval":10,"reportable_change":100},{"attribute":"batteryPercentageRemaining","cluster":"genPowerCfg","maximum_report_interval":62000,"minimum_report_interval":3600,"reportable_change":0},{"attribute":"acceleration","cluster":"manuSpecificSamsungAccelerometer","maximum_report_interval":60,"minimum_report_interval":10,"reportable_change":1},{"attribute":"x_axis","cluster":"manuSpecificSamsungAccelerometer","maximum_report_interval":60,"minimum_report_interval":10,"reportable_change":1},{"attribute":"y_axis","cluster":"manuSpecificSamsungAccelerometer","maximum_report_interval":60,"minimum_report_interval":10,"reportable_change":1},{"attribute":"z_axis","cluster":"manuSpecificSamsungAccelerometer","maximum_report_interval":60,"minimum_report_interval":10,"reportable_change":1}]}},"friendly_name":"door","ieee_address":"0x286d970001097a6d","interview_completed":true,"interviewing":false,"model_id":"multi","network_address":22174,"power_source":"Battery","software_build_id":"","supported":true,"type":"EndDevice"},{"date_code":"04-25-2018","definition":{"description":"Aqara double key wired wall switch without neutral wire. Doesn't work as a router and doesn't support power meter","exposes":[{"endpoint":"left","features":[{"access":7,"description":"On/off state of the switch","endpoint":"left","name":"state","property":"state_left","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"endpoint":"right","features":[{"access":7,"description":"On/off state of the switch","endpoint":"right","name":"state","property":"state_right","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":1,"description":"Measured temperature value","name":"temperature","property":"temperature","type":"numeric","unit":"°C"},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["single_left","single_right","single_both"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"QBKG03LM","supports_ota":true,"vendor":"Xiaomi"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genIdentify","genPowerCfg","genDeviceTempCfg","genOta","genTime"],"output":["genBasic","genTime","genOta"]},"configured_reportings":[]},"2":{"bindings":[],"clusters":{"input":["genBinaryOutput","genOnOff","genGroups","genScenes"],"output":[]},"configured_reportings":[]},"3":{"bindings":[],"clusters":{"input":["genBinaryOutput","genOnOff","genGroups","genScenes"],"output":[]},"configured_reportings":[]},"4":{"bindings":[],"clusters":{"input":["genMultistateInput","genOnOff"],"output":[]},"configured_reportings":[]},"5":{"bindings":[],"clusters":{"input":["genMultistateInput","genOnOff"],"output":[]},"configured_reportings":[]},"6":{"bindings":[],"clusters":{"input":["genMultistateInput","genOnOff"],"output":[]},"configured_reportings":[]},"8":{"bindings":[],"clusters":{"input":["genAnalogInput"],"output":[]},"configured_reportings":[]}},"friendly_name":"Switch","ieee_address":"0x00158d00041a2bb2","interview_completed":true,"interviewing":false,"model_id":"lumi.ctrl_neutral2","network_address":56892,"power_source":"DC Source","supported":true,"type":"EndDevice"},{"date_code":"20201117","definition":{"description":"Hue white GU10 bluetooth","exposes":[{"features":[{"access":7,"description":"On/off state of this light","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"},{"access":7,"description":"Brightness of this light","name":"brightness","property":"brightness","type":"numeric","value_max":254,"value_min":0}],"type":"light"},{"access":2,"description":"Triggers an effect on the light (e.g. make light blink for a few seconds)","name":"effect","property":"effect","type":"enum","values":["blink","breathe","okay","channel_change","finish_effect","stop_effect"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"LWG004","supports_ota":true,"vendor":"Philips"},"endpoints":{"11":{"bindings":[],"clusters":{"input":["genBasic","genIdentify","genGroups","genScenes","genOnOff","genLevelCtrl","touchlink","manuSpecificSamsungAccelerometer"],"output":["genOta"]},"configured_reportings":[]},"242":{"bindings":[],"clusters":{"input":[],"output":["greenPower"]},"configured_reportings":[]}},"friendly_name":"Philips lamp","ieee_address":"0x0017880108c703a1","interview_completed":true,"interviewing":false,"model_id":"LWG004","network_address":57729,"power_source":"Mains (single phase)","software_build_id":"1.76.11","supported":true,"type":"Router"},{"date_code":"22/04/2021 11:13","definition":{"description":"[Flower sensor](http://modkam.ru/?p=1700)","exposes":[{"access":1,"description":"Measured soil moisture value","name":"soil_moisture","property":"soil_moisture","type":"numeric","unit":"%"},{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Raw measured illuminance","name":"illuminance","property":"illuminance","type":"numeric"},{"access":1,"description":"Measured relative humidity","name":"humidity","property":"humidity","type":"numeric","unit":"%"},{"access":1,"description":"The measured atmospheric pressure","name":"pressure","property":"pressure","type":"numeric","unit":"hPa"},{"access":1,"description":"Measured temperature value","endpoint":"ds","name":"temperature","property":"temperature_ds","type":"numeric","unit":"°C"},{"access":1,"description":"Measured temperature value","endpoint":"bme","name":"temperature","property":"temperature_bme","type":"numeric","unit":"°C"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"DIYRuZ_Flower","supports_ota":false,"vendor":"DIYRuZ"},"endpoints":{"1":{"bindings":[{"cluster":"genPowerCfg","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}},{"cluster":"msRelativeHumidity","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}},{"cluster":"msPressureMeasurement","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}},{"cluster":"msIlluminanceMeasurement","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}},{"cluster":"msSoilMoisture","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}},{"cluster":"msTemperatureMeasurement","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}}],"clusters":{"input":["genBasic"],"output":["genPowerCfg","msIlluminanceMeasurement","msTemperatureMeasurement","msPressureMeasurement","msRelativeHumidity","msSoilMoisture"]},"configured_reportings":[{"attribute":"batteryVoltage","cluster":"genPowerCfg","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0},{"attribute":"batteryPercentageRemaining","cluster":"genPowerCfg","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0},{"attribute":"measuredValue","cluster":"msTemperatureMeasurement","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0},{"attribute":"measuredValue","cluster":"msRelativeHumidity","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0},{"attribute":"scaledValue","cluster":"msPressureMeasurement","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0},{"attribute":"measuredValue","cluster":"msIlluminanceMeasurement","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0},{"attribute":"measuredValue","cluster":"msSoilMoisture","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0}]},"2":{"bindings":[{"cluster":"msTemperatureMeasurement","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}}],"clusters":{"input":[],"output":["msTemperatureMeasurement"]},"configured_reportings":[{"attribute":"measuredValue","cluster":"msTemperatureMeasurement","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0}]}},"friendly_name":"Растишка","ieee_address":"0x00124b0022ffa598","interview_completed":true,"interviewing":false,"model_id":"DIYRuZ_Flower","network_address":60264,"power_source":"Battery","software_build_id":"22/04/2021 11:13","supported":true,"type":"EndDevice"},{"date_code":"09-10-2019","definition":{"description":"Aqara EU smart plug","exposes":[{"features":[{"access":7,"description":"On/off state of the switch","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":1,"description":"Instantaneous measured power","name":"power","property":"power","type":"numeric","unit":"W"},{"access":1,"description":"Sum of consumed energy","name":"energy","property":"energy","type":"numeric","unit":"kWh"},{"access":1,"description":"Measured temperature value","name":"temperature","property":"temperature","type":"numeric","unit":"°C"},{"access":1,"description":"Measured electrical potential value","name":"voltage","property":"voltage","type":"numeric","unit":"V"},{"access":1,"description":"Instantaneous measured electrical current","name":"current","property":"current","type":"numeric","unit":"A"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"SP-EUC01","supports_ota":true,"vendor":"Xiaomi"},"endpoints":{"1":{"bindings":[{"cluster":"genOnOff","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}},{"cluster":"haElectricalMeasurement","target":{"endpoint":1,"ieee_address":"0x00124b0018f1da45","type":"endpoint"}}],"clusters":{"input":["genBasic","genDeviceTempCfg","genIdentify","genGroups","genScenes","genOnOff","genAlarms","seMetering","haElectricalMeasurement"],"output":["genTime","genOta"]},"configured_reportings":[{"attribute":"onOff","cluster":"genOnOff","maximum_report_interval":3600,"minimum_report_interval":0,"reportable_change":0}]},"242":{"bindings":[],"clusters":{"input":[],"output":["greenPower"]},"configured_reportings":[]}},"friendly_name":"aqara plug","ieee_address":"0x04cf8cdf3c89f723","interview_completed":true,"interviewing":false,"model_id":"lumi.plug.maeu01","network_address":58109,"power_source":"Mains (single phase)","supported":true,"type":"Router"}]`

`{"battery":100,"humidity":null,"illuminance":1249,"illuminance_lux":1,"linkquality":42,"pressure":null,"soil_moisture":86,"temperature_bme":null,"temperature_ds":32.25,"voltage":3100}`

**Comment by itavero** [comment] 2021-07-18 16:22
I had a look at the exposes information you've provided (after formatting it).

* `soil_mosture` is not something that is currently supported by this plugin. As far as I know there's also no official HomeKit Characteristic/Service for it. If you know of an official HomeKit device that exposes a similar Characteristic, it might be possible to reverse engineer it. Anyway, if you wish to add support for this, please open up a feature request and fill in the requested information in the template.
* `illuminance` is not supported by the plugin, as there is no unit associated with it. The official [Current Ambient Light Level](https://developers.homebridge.io/#/characteristic/CurrentAmbientLightLevel) characteristic expects a value in _lux_.

As far as I can tell from your Home.app screenshot, all the properties exposed by the device that are supported by this plugin are correctly transformed into HomeKit Services & Characteristics.

With regards to the warning about the `null` value: I'm working on a fix to filter out all undefined/null values from state updates, which will be released soon.

**Closed by itavero** 2021-07-18 16:22 UTC
Labels: bug

**Comment by itavero** [comment] 2021-08-16 19:55
v1.4.0 has been released

**Comment by WojtekWro** [comment] 2022-04-21 15:01
Hi @itavero
I know this issue is closed, however I would like to ask about your opinion. 
I know that the "soil measure" is not supported by HomeKit, but maybe is it possible to show it as humidity in HK? 
So fare this is only sensor which I can use to check if my lawn needs water :-)

**Comment by itavero** [comment] 2022-04-21 20:01
@WojtekWro Please open a feature request issue and describe the functionality you are looking for, then I'll try to look into it.
