### ISSUE TITLE
[Feature] IKEA Switches show as “Not Supported"

### ISSUE THREAD

**Issue by EdwardChamberlain** [itavero/homebridge-z2m#33] opened 2020-12-22 17:59 UTC
**Problem description**
Ikea wireless "dimmer" switches present as "not supported" in the home app.
Device: https://www.ikea.com/gb/en/p/tradfri-wireless-dimmer-white-00468432/

**Suggested solution**
Present this as a programable stateless switch. 

**Describe alternatives you've considered**
The Zigbee-NT plugin presents these as stateless swtiches. 
Home assistant presents these as "sensors" (which ends up causing issues getting them to work)
The MQTT Thing plugin offers programable stateless switch options. 

**Additional context**
Expected Behaviour: https://imgur.com/a/YGoxKUP

**Are you willing to contribute to this feature?**
Yes - can supply MQTT data, test etc but don't have the programming skills to implement a solution.

**Comment by itavero** [comment] 2020-12-22 18:16
Duplicate of #2

**Comment by itavero** [comment] 2020-12-22 18:23
@EdwardChamberlain, as far as I can tell this is a duplicate of #2.

I've almost reached a point where I can create a "beta" version of the changes made in #18.
These changes should make it possible to start implementing support for switches. I have a very clear understanding of how this feature can be implemented, as I've also described in #2.

Closing this issue because of the duplication.
If you have any additional information or requests related to this, please add it to the existing issue.

**Closed** 2020-12-22 18:23 UTC
Labels: enhancement
