### ISSUE TITLE
[Device] TuYa GDC311ZBQ1

### ISSUE THREAD

**Issue by Ropuh** [itavero/homebridge-z2m#605] opened 2023-01-05 08:16 UTC
### Device Model

TuYa GDC311ZBQ1

### Is there an existing issue for this?

- [X] I have searched the existing issues and did not find an existing issue.

### Supported by Zigbee2MQTT?

- [X] Device is supported by Zigbee2MQTT

### Missing features / functionality

Missing support ny zigbee2mqtt-zm

### HomeKit Services and Characteristics

Garage_door_contact
Open_door
Close_door

### Exposes information from Zigbee2MQTT

```json
[
  {
    "type": "binary",
    "name": "trigger",
    "property": "trigger",
    "access": 3,
    "value_on": true,
    "value_off": false,
    "description": "Trigger the door movement"
  },
  {
    "type": "binary",
    "name": "garage_door_contact",
    "property": "garage_door_contact",
    "access": 1,
    "value_on": false,
    "value_off": true,
    "description": "Indicates if the garage door contact is closed (= true) or open (= false)"
  },
  {
    "type": "numeric",
    "name": "linkquality",
    "property": "linkquality",
    "access": 1,
    "unit": "lqi",
    "description": "Link quality (signal strength)",
    "value_min": 0,
    "value_max": 255
  }
]
```

**Comment by itavero** [comment] 2023-01-05 12:58
Duplicate of #594 / #471 / #444. Please continue the discussion in #444

**Closed by itavero** 2023-01-05 12:58 UTC
Labels: enhancement
