### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sateeshruttala** [itavero/homebridge-z2m#801] opened 2024-01-03 06:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

getting this error not able to see anything in homebridge 

 [1/3/2024, 5:49:10 PM] [zigbee2mqtt] Failed to process MQTT message on 'zigbee2mqtt/bridge/devices'. (Maybe check the MQTT version?)
[1/3/2024, 5:49:10 PM] [zigbee2mqtt] Cannot read properties of null (reading 'vendor')

### This plugin

1.9.2

### Homebridge

1.7.0

### Zigbee2MQTT

1.35.0

### Homebridge Config UI X (if applicable)

4.54.2

**Comment by itavero** [comment] 2024-01-03 11:42
Seems like a duplicate of #794

Please try  [v1.9.3-rc.0](https://www.npmjs.com/package/homebridge-z2m/v/1.9.3-rc.0)

**Closed by itavero** 2024-01-03 11:42 UTC
Labels: bug
