### ISSUE TITLE
[Bug] Device name in Home.app

### ISSUE THREAD

**Issue by Jeepmg** [itavero/homebridge-z2m#578] opened 2022-12-04 08:26 UTC
Please use the template and fill in all the data requested below!

**Describe the bug**
When you change the name of a device in Z2M, this name is change in Homebridge-Z2M but not in Home.app

**Related devices**
tested with 2 devices, same behavious

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Change the name of a device in Z2M
2. Check the new name in Homebridge-Z2M
3. Check the name in Apple Homekit

**Versions used**
Please provide the version of the following pieces of software:
 - Last for all

**Comment by itavero** [comment] 2022-12-04 08:35
Possible duplicate of/related to #76 / #473

**Comment by Jeepmg** [comment] 2022-12-04 08:47
Not really the same as https://github.com/itavero/homebridge-z2m/issues/76 / https://github.com/itavero/homebridge-z2m/issues/473.

> Have you tried restarting Homebridge and the Home.app?

YES

> Unfortunately, as you have mentioned, the name is changed in Homebridge, right?

YES

> Unfortunately I don't think there's a lot I can do about that.

I will do it myself by hand

Thank you

**Closed** 2022-12-09 18:17 UTC
Labels: bug
