### ISSUE TITLE
[Bug] TuYa GDC311ZBQ1

### ISSUE THREAD

**Issue by lenny005** [itavero/homebridge-z2m#471] opened 2022-06-27 20:22 UTC
**Describe the bug**

Device not compatible in Home.

**Related devices**

Modèle Zigbee
TS0601
Constructeur Zigbee
_TZE200_wfxuhoea
Description
LoraTap garage door opener with wireless sensor

**To Reproduce**

Added device via Zigbee2Mqtt and it is recognized but not compatible in Home. Worked with HA.

**Expected behavior**
Like any other gare goor opener zigbee device, to state when open/close and trigger the door

**Versions used**
Please provide the version of the following pieces of software:
 - Plugin 1.8.0
 - Homebridge 1.5
 - Zigbee2MQTT [1.25.2] commit: [9b2a921]
 - Homebridge Config UI X 4.48.1

**Comment by itavero** [comment] 2022-06-27 20:57
This page clearly states that this device is not (yet) supported by this plugin, so definitely not a bug but working as intended.

The feature you are requesting seems to be the same as #444. Closing as duplicate.

**Closed** 2022-06-27 20:57 UTC
Labels: bug
