### ISSUE TITLE
[Feature] Provide Groups from z2m to HomeKit

### ISSUE THREAD

**Issue by Z18Aplha** [itavero/homebridge-z2m#277] opened 2021-09-07 10:14 UTC
First, i want to say, i love this plugin. It works perfect for me.

But i would like the request a feature. I already read #166 but i would like to start a new "issue" for that.

**What would be cool**
All groups from zigbee2mqtt are exposed in HomeKit.
Different to #166 it is not required to subsequently hide all devices assigned to a group. Sometimes it is still necessary to keep each device next to the group. Nevertheless, excluding unwanted devices is already possible.
Just adding a new "device" to HomeKit would be great.

**Why this would be cool**
Because sending a command to a group needs just one zigbee transmission. The devices assigned to a group react simultaneously and thats beautiful. Especially when it comes to range problems, a group is much more reliable than sending 8 commands to 8 lightbulbs. 

**How this could be accomplished**
 There should be no differences to exposing a device, because the mqtt topics are the friendly name of the group (assigned in zigbee2mqtt) and are exposed by in its seperate mqtt topic, just like the devices.
A hurdle is, "zigbee2mqtt/bridge/groups" does not provide any functions of its members. So it becomes necessary to assign a device to the group in Homebridge.
Otherwise, i think an auto-detect of groups is not necessary at all. With adding "groups" to the config.json and enumerate each friendly name of the group you want to use and assign a device group (lightbulb RGB or whatever) should do the job.

Thanks for attention :)

**Comment by itavero** [comment] 2021-09-17 17:04
Duplicate of #166, which was closed due to inactivity.

If I have some time, I'll try to experiment with this a bit to get a feel for how it works and can be integrated.

**Comment by jacktho** [comment] 2021-09-18 17:46
> Duplicate of #166, which was closed due to inactivity.
> 
> If I have some time, I'll try to experiment with this a bit to get a feel for how it works and can be integrated.

That would be wonderful if you do get time to look at it. I'm in the same boat. Everything works great but groups would make things happen faster and more seamless. I have a lot of devices.

**Comment by JeanMertz** [comment] 2021-10-29 18:14
I'd love to see this land as well. (sorry for the "me too" comment, but apparently the `stale` bot doesn't recognize +1 emojis added to the issue)

**Comment by itavero** [comment] 2021-11-19 20:30
I've recently created some groups in my setup at home to get a feeling for how it works and to have an environment I can try some things on.

"Unfortunately" I also have some other projects I'm working on in my spare time, so no promises yet on if/when I'll start working on this feature.

**Comment by itavero** [comment] 2021-12-02 05:55
I have some ideas on how to approach this, but first I want to add a "generic" mechanism to enable _experimental_ features from the plugin configuration (i.e. _feature flags_).

This would allow me to include some of the other improvements/changes I've been working on, but aren't yet fully to my satisfaction. Users could try them out if they want to, so I can gather feedback before releasing it to everyone.

**Comment by itavero** [comment] 2021-12-05 19:30
I think a found a decent way to try and figure out the `exposes` information for a group.

Of course, in reality, it all depends on the endpoints being added to the group and how the relate to the provided `exposes` information. As this link is not known, it's still a "best guess", but what I have so far seems to give the right information for the groups I have.

I think I will still need to add the possibility to manually provide the `exposes` information via the `config.json` for the groups where this mechanism might not work.

Next time I work on this, I'll look into how the current `Zigbee2mqttAccessory` class should be adjusted / split up for supporting groups.

I'm also not yet sure what the default behavior should be for accessories that are also part of a group. I think it makes sense to have the option to hide these accessories in HomeKit via the configuration, but should this be the default or not.. 🤔

**Comment by JeanMertz** [comment] 2021-12-06 08:25
Awesome progress update 👍



> I'm also not yet sure what the default behavior should be for accessories that are also part of a group. I think it makes sense to have the option to hide these accessories in HomeKit via the configuration, but should this be the default or not.. 🤔

For me personally, hiding them by default makes sense, but I don't particularly mind one way or the other, it's not like you add new devices daily, so having to configure this once or twice a year is no problem.

**Comment by vdebrist** [comment] 2021-12-19 17:20
Dear @itavero 

How can I test your build "support-for-groups"? 
command `npm install homebridge-z2m@support-for-groups` not worked :(

**Comment by itavero** [comment] 2021-12-19 18:01
Nothing to test yet. I haven't had time yet to continue my work on it.

**Comment by itavero** [comment] 2021-12-20 19:39
Added support for groups as an experimental feature (enabled with flag `GROUPS`, see [docs on configuration](https://z2m.dev/config.html#experimental)) in `v1.7.0-rc.1` (also tagged as `homebridge-z2m@next` on NPM).

I'll start running this feature in my production environment (a.k.a. my home) to see how well it works.

If you've tried it out and have any suggestions/issues, please reply on this issue.

**Comment by Z18Aplha** [comment] 2021-12-24 12:20
Thank you for the implementation. 
I will test the feature in the next weeks. 👍

**Comment by itavero** [comment] 2021-12-29 09:01
Found a couple of things (see comment above) that still need to be improved in my opinion.

If you have any feedback with regards to this feature, let me know.

(cc @JeanMertz @vdebrist @jacktho @Z18Aplha @mpuff @Luftloch80 @chrisjansky )

**Comment by itavero** [comment] 2021-12-29 09:05
If anyone has grouped devices that use different _properties_ for the same thing (i.e. for `state` they have `state_l1` or something like that). I wonder what their experiences are.

I think they will not work out of the box right now, as the "auto-exposes-detection" thingy only combines entries for which the _property_ also matches.
Perhaps in these cases it is also fine if the `name` is used instead of the `property`, but I'm not sure if that works.

**Comment by jacktho** [comment] 2022-01-04 04:17
Looks good so far! Light changes are much more responsive now and it's satisfying that all the lights change in perfect sync.

I'll report back if I have any other feedback when I have more time to tinker. I'll have to check if I have devices with differing property names.

Thanks!

**Comment by jacktho** [comment] 2022-01-06 03:51
@itavero Is `"exclude_grouped_devices": true` still working for you?

Devices in a Zigbee2mqtt group are still showing up individually in Homekit for me in addition to the group. I've tried restarting Homebridge and even nuking Homebridge and starting fresh.

**Comment by itavero** [comment] 2022-01-06 05:29
> @itavero Is `"exclude_grouped_devices": true` still working for you?

I'm not using this option in my "production" environment. I've only tested it manually on my development machine. I've added it to my list of _Open issues_ in my earlier comment.

**Comment by itavero** [comment] 2022-01-10 16:01
> @itavero Is `"exclude_grouped_devices": true` still working for you?

Can you turn on debug logging in see if you see something like `Device (0x ...) is excluded because it is in a group:` in the logs?

**Comment by Z18Aplha** [comment] 2022-01-18 01:26
@itavero i dont know what i am doing wrong.
I added ```""experimental": ["GROUPS"]``` to my config but no groups appear in HomeKit. Even the log shows nothing but ```Experimental features enabled: GROUPS```. I tested version 1.3.9 and 1.4.0 beta (the version number on status page) and my homebridge is in a docker container. 
I have no clue, what i am doing wrong.

**Comment by itavero** [comment] 2022-01-18 05:25
> But unfortunately the ```"exclude_grouped_devices"``` key doesn't work for me. 

Can you perhaps turn on debug logging and see what the logs say?
Also, where did you put this in the plugin configuration?

**Comment by itavero** [comment] 2022-02-01 10:43
@jacktho and/or @Z18Aplha, with regards to `exclude_grouped_devices`, may I ask where you put this in the plugin configuration (or did you perhaps use Config UI X)?

So far I have been unable to reproduce it on my end, hence the question.

**Comment by jacktho** [comment] 2022-02-07 18:14
> > @itavero Is `"exclude_grouped_devices": true` still working for you?
> 
> Can you turn on debug logging in see if you see something like `Device (0x ...) is excluded because it is in a group:` in the logs?
> 
> I did a check on my development environment and there I can see that the devices are being excluded.

With homebridge debug mode on there is not a message like that in my logs.

At startup there is:

> Initializing zigbee2mqtt platform...
Experimental features enabled: GROUPS
Default device config: {"excluded":false,"exclude":false}
Connecting to MQTT server at mqtt://docker-vm.pvt:1883
Using MQTT keepalive: 60
MQTT reject_unauthorized set false, ignoring certificate warnings.

And then for each device including ones in a group:

> Restoring accessory: light-kitchen-ceiling-6 (0xf0d1b8000001c321)
Config for accessory light-kitchen-ceiling-6 : {"excluded":false,"exclude":false}

**Comment by jacktho** [comment] 2022-02-07 18:26
> @jacktho and/or @Z18Aplha, with regards to `exclude_grouped_devices`, may I ask where you put this in the plugin configuration (or did you perhaps use Config UI X)?
> 
> So far I have been unable to reproduce it on my end, hence the question.

I think I did originally use the webgui. The settings for the plugin show:
![image](https://user-images.githubusercontent.com/8503272/152847629-4d27c9d7-fea2-461e-b29f-2b5d78ab9a58.png)
![image](https://user-images.githubusercontent.com/8503272/152847651-aad6d00c-9dcb-4f3c-bb85-5e660b247982.png)

The logs show:
> Homebridge Config Path: /homebridge/config.json

And that config.json has:

```json
{
    "bridge": {
        "name": "....",
        "username": "...",
        "port": ...,
        "pin": "..."
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "mqtt": {
                "base_topic": "zigbee2mqtt",
                "server": "mqtt://docker-vm.pvt:1883",
                "reject_unauthorized": false,
                "keepalive": 60,
                "version": 4,
                "disable_qos": false
            },
            "defaults": {
                "exclude": false
            },
            "exclude_grouped_devices": true,
            "experimental": [
                "GROUPS"
            ],
            "platform": "zigbee2mqtt"
        }
    ]
}
```

**Comment by Z18Aplha** [comment] 2022-02-16 20:42
> @jacktho and/or @Z18Aplha, with regards to `exclude_grouped_devices`, may I ask where you put this in the plugin configuration (or did you perhaps use Config UI X)?
> 
> So far I have been unable to reproduce it on my end, hence the question.

@itavero I'm sorry for my delayed answer. I am workin on my thesis at the moment, so there wasn't much time for me to work on my smart home that much.

My .json config ist

```json
{
    "mqtt": {
        "base_topic": "zigbee2mqtt",
        "server": "mqtt://192.168.7.10:1883",
        "client_id": "homebridge",
        "reject_unauthorized": false,
        "keepalive": 60,
        "version": 4,
        "disable_qos": false
    },
    "defaults": {
        "exclude": false,
        "excluded_keys": [
            "temperature",
            "window_detection"
        ]
    },
    "exclude_grouped_devices": true,    
    "experimental": [
        "GROUPS"
    ],
    "platform": "zigbee2mqtt"
}
```

The dev log shows nothing like "Device excluded because of group". Instead the log shows for the most of the devices "Restoring 0x.....". I hope my answer helps.

**Comment by mpuff** [comment] 2022-02-16 21:36
exclude_grouped_devices is working for me.

**Comment by itavero** [comment] 2022-02-17 05:31
I see. You both have `exclude` set to `false` in your default device config. This will (indirectly) overrule the decision made by `exclude_grouped_devices`.

It made sense to me to use the `exclude` option to "undo" the exclusion of certain grouped devices.

Can you confirm that not setting `exclude` in the `defaults` section resolves the issue?

**Comment by Z18Aplha** [comment] 2022-02-17 11:02
> I see. You both have `exclude` set to `false` in your default device config. This will (indirectly) overrule the decision made by `exclude_grouped_devices`.
> 
> It made sense to me to use the `exclude` option to "undo" the exclusion of certain grouped devices. I wasn't expecting that users would have it set to `false` by default, as that's already the default behavior of the plugin if it is not set. I guess I can also just filter out the option from the defaults if it is set to `false`, in a future version.
> 
> Can you confirm that not setting `exclude` in the `defaults` section resolves the issue, @jacktho / @Z18Aplha ?
> 
> PS: Good luck on your thesis, @Z18Aplha !

I'm not sure, why i set exclude to false in the defaults, but i think i saw it in an example config. 
But i can confirm that not setting it to false SOLVED the problem. My grouped devices disappeared from my Home app. PERFECT thanks! 👍 

PS: Thank you :)

**Comment by itavero** [comment] 2022-02-17 11:05
As mentioned, I'll update the plugin to simply ignore `exclude` in the `defaults` if it is set to `false`, should not really result in any different behavior, apart from this new feature.
I can imagine that if you both ended up with this configuration somehow, that others will have it as well.

**Comment by jacktho** [comment] 2022-02-17 13:13
@itavero Yep that got it working. I also am not sure how that ended up in my config.

Thanks!

**Comment by Z18Aplha** [comment] 2022-02-17 23:12
> As mentioned, I'll update the plugin to simply ignore `exclude` in the `defaults` if it is set to `false`, should not really result in any different behavior, apart from this new feature.
> I can imagine that if you both ended up with this configuration somehow, that others will have it as well.

Yeah that should be the right approach. Apparently I am not alone with this „useless“ config and there might be others too.

**Comment by Z18Aplha** [comment] 2022-02-17 23:13
> > As mentioned, I'll update the plugin to simply ignore `exclude` in the `defaults` if it is set to `false`, should not really result in any different behavior, apart from this new feature.
> > I can imagine that if you both ended up with this configuration somehow, that others will have it as well.
> 
> Yeah that should be the right approach. Apparently I am not alone with this „useless“ config and there might be others too.

Thank you for your efforts! :)

**Comment by itavero** [comment] 2022-02-20 16:46
FYI: Just released v1.7.0 with the fixes mentioned earlier.

**Comment by TeslaCLT** [comment] 2022-02-21 21:38
The groups feature is working perfectly for me. So far I've only merged like devices (3 pack of identical bulbs vs. 3 bulbs from different manufacturers), but it has been great. No more them turning on/off in a series and instead they all behave as a proper group. I've then been able to leverage this functionality to expose my group to Alexa and Google Home for voice control. Thanks!

FYI, the exclude group devices worked as intended for me. I, like others here, have exclude set to false in my defaults.

**Comment by itavero** [comment] 2022-05-09 16:03
FYI: I plan to enable support for groups by default in the next release, so the experimental flag will no longer be required after that.

**Closed** 2022-05-09 16:25 UTC
Labels: enhancement

**Comment by smulle48** [comment] 2022-07-02 16:09
> FYI: I plan to enable support for groups by default in the next release, so the experimental flag will no longer be required after that.

Is there a way to disable this by default, and only include specific groups?

As ikea has removed native groups in the latest firmware for the buttons, I'm running the old firmware that does allow this. The downside is that every bulb has to been in an group, even if it's only one bulb.

Then problem with this, is that I then get both a group (with one bulb) and the bulb itself.

The same goes for the blinds that has to be in a group.

If I try to exclude the group, by friendly name, zigbee2mqtt throws a lot of errors that it could not get the state of every item.

**Comment by itavero** [comment] 2022-07-02 16:41
> Is there a way to disable this by default, and only include specific groups?

Not at this time, but something like that can certainly be made. Can you perhaps create a new feature request for this, and also elaborate on what you've already tried and the errors you got?

**Comment by JeanMertz** [comment] 2022-07-04 10:30
Quick note that one thing I noticed, is that for all my lights and groups created in Homekit (using z2mqtt and homebridge), changing the brightness results in a smooth transition between the two values, but for groups created in z2mqtt and exposed through homebridge, the transition is instant.

**Comment by itavero** [comment] 2022-07-04 10:48
> Quick note that one thing I noticed, is that for all my lights and groups created in Homekit (using z2mqtt and homebridge), changing the brightness results in a smooth transition between the two values, but for groups created in z2mqtt and exposed through homebridge, the transition is instant.

Do you have a default `transition` set in Zigbee2MQTT perhaps?
It could be that those don't apply to groups in Zigbee2MQTT itself. 🤔

**Comment by JeanMertz** [comment] 2022-07-04 18:29
> Do you have a default `transition` set in Zigbee2MQTT perhaps?

I do have `device_options.transition` set to `1`, yes.

**Comment by itavero** [comment] 2022-07-04 22:48
> I do have `device_options.transition` set to `1`, yes.

I guess that doesn't apply to groups then. If you'd like to try and get that fixed, you should probably head over to the Zigbee2MQTT repository and create an issue there. The plugin sends the command exactly the same for groups as it does got individual devices.
